### PR TITLE
 Master - Selenium FAQ customer tests

### PR DESCRIPTION
**Pull request by s7design**
Hi @carlosfrodriguez ,

Here are selenium tests for FAQ Customer modules. If there are any question, please let me know.

Regards,
Sanjin

### CODE REVIEW

**Comment by carlosfrodriguez** [comment]
Hi @s7design, Sanjin,

I have problems with this unit tests, it might be because I had a lot of FAQs due to the previous tests, but either of the FAQ is not found or the customer does no have rights, can you please review all the tests again?

((enjoy))
cr

**Comment by s7design** [comment]
Hi @carlosfrodriguez 

We will check it again and if it is possible, provide update of this PR. It will be done soon.

Regards
Zoran

**Comment by s7design** [comment]
HI @carlosfrodriguez ,

I updated CustomerFAQSearch, it could pose a problem on the end of test if there were FAQs left from previous tests. Try them now and if there are any issues, please let me know.

Regards,
Sanjin

**Comment by s7design** [comment]
Hi @carlosfrodriguez ,

There has been some difficulties still with CustomerFAQSearch modules. With latest commit i have been working on OTRS version from couple of days ago. Seems like there has been some recent updates that cause CustomerFAQSearch to crash on opening. From preliminary research it seems that javascript crash it. Will investigate this issue further on and let you know once we determinate problem that cause it.

Regards,
Sanjin

**Comment by s7design** [comment]
Hi @carlosfrodriguez 

This PR is also rebased on master. There is a problem with InitFocus in search screen. Now tests works for me.

Regards
Zoran

**Comment by carlosfrodriguez** [comment]
Hi @s7design, Sanjin, Zoran

Thank you all for the pull request and for the followups, I found that the issue I was expecting was because the Approval function on my installation was enabled, and the FAQ Items where created unapproved, then the customers doesn't had added to them.

I merge the pull request in https://github.com/OTRS/FAQ/commit/407242860e828212d52fb79bd3c6bca83e1a31ed, with pre-approved FAQ Items. BTW creation of test customer users does not use the Group attribute, it can only use Language, so I removed the Group attributes in all tests.

((enjoy))
cr

**Pull request closed without merging**
