### PR TITLE
Marked strings as translatable

### PR DESCRIPTION
**Pull request by urbalazs**
Hi @carlosfrodriguez 
This PR replaces https://github.com/OTRS/FAQ/pull/26, because I have to rebase again. Please, check these changes.

### CODE REVIEW

**Comment by urbalazs** [comment]
Hi @carlosfrodriguez 
My original proposal is almost one year old! I have to rebase is two times, and finally I made this one. Please, check this PR!
I guess, there will be a new release soon. If this PR will be applied, then need to sync with Transifex. I like to make the translation of these new strings for the next release (for 5.0.11).

**Comment by urbalazs** [comment]
Hi @carlosfrodriguez  and @mgruner  
Can you check this pull request? My original proposal is more than one year old.

**Comment by urbalazs** [comment]
Hi @carlosfrodriguez 
Can you check this PR? It adds more translatable strings to language files.

**Comment by urbalazs** [comment]
Hi @carlosfrodriguez
Can you check this PR? It adds more translatable strings to language files.

**Comment by carlosfrodriguez** [comment]
Hi @urbalazs,

Thank you for your pull request and your patience, it was merged in https://github.com/OTRS/FAQ/commit/448fabd68576f439f68dae53dd2ce07acde791cf, with small modifications. (it was not passing our OTRSCodePolicy checks).

((enjoy))
cr

**Pull request closed without merging**
