### PR TITLE
Fixed Limit and FetchrowArray() wrapped in while

### PR DESCRIPTION
**Pull request by k-mx**

### CODE REVIEW

**Comment by mgruner** [comment]
Hi @k-mx, this looks like a valid code fix. @s7design, can you please verify and handle this?

**Comment by k-mx** [comment]
My bad, I should have explained. This is not bugfix, but:
1. Why we use `Limit => $Param{Limit} || 500,` if query will always return 1 row?
2. Due to OTRS code style guide, we must always wrap FetchrowArray() into while loop

**Comment by mgruner** [comment]
@k-mx I agree, and therefore consider it a "bugfix", even if it might not trigger a bug that the user can see.

**Comment by s7design** [comment]
Applied, thanks a lot @k-mx!

There is commit:
https://github.com/OTRS/FAQ/commit/85d1b7c4bb87dd6e71969c3e79a66e83cafddccd

Regards
Zoran

**Pull request closed without merging**
