### PR TITLE
[ Master FAQ Bug 12406 ] - Fixed FAQ keyword search issue and modified Unit test

### PR DESCRIPTION
**Pull request by s7design**
https://bugs.otrs.org/show_bug.cgi?id=12406

Hi @carlosfrodriguez 

Hereby is proposal for reported bug fix. Keywords for searching are splitted by space and all of them are added to SQL inquiry.
Unit test is modified for case with multiple keywords.
Please let me know if you have any comment for this PR.

Regards
Zoran

### CODE REVIEW

**Comment by carlosfrodriguez** [comment]
Hi @s7design,

What about use QueryCondition instead?

**Comment by s7design** [comment]
Hi @carlosfrodriguez 

Thanks for suggestion, we tried to fix it with QueryCondition but I suppose we did not use param of the method QueryCondition in good way and I thought it is not possible that we fix this bug with this method. 

Now, I tried again and you are right it is better way how we can fix this bug. We will provide new solution very soon.

Regards
Zoran

**Comment by s7design** [comment]
Hi @carlosfrodriguez 

QueryCondition is added and Unit test is modified.

Regards
Zoran

**Comment by carlosfrodriguez** [comment]
Hi @s7design,

Thank you for your pull request, it was merged in https://github.com/OTRS/FAQ/commit/5837a26db91c445e5d5b3e5535fb8cd2d50da082 and https://github.com/OTRS/FAQ/commit/48dfaf20dba16c91263adf5f164a650202bc911e with minor changes and added a couple more tests.

((enjoy))
cr

**Pull request closed without merging**
