### PR TITLE
[Master Bug 11498] - FAQ items dissapear from AgentFAQExplorer when invalid

### PR DESCRIPTION
**Pull request by s7design**
http://bugs.otrs.org/show_bug.cgi?id=11498
Hi @carlosfrodriguez 

Here is our proposal for fixing this bug. 
My idea was that we allow agents to see invalid FAQ items. I believe that this feature is not needed for customer and public interface. Please, let me know what do you think about that.

Regards
Zoran

### CODE REVIEW

**Comment by s7design** [comment]
Hi @carlosfrodriguez

I rebased this PR to make it up to date with the changes which have been happened in meantime.

Regards
Zoran

**Comment by carlosfrodriguez** [comment]
Hi @s7design,

The code and the functionality looks very nice. would it be possible to extend unit tests for the core function additions?

((enjoy))
cr

**Comment by s7design** [comment]
Hello @carlosfrodriguez ,

Modified Selenium tests to check for invalid FAQ's with and without enabled newly added sysconfig item.

Please let me know if you want any additional testing regarding this bug.

Regards,
Sanjin

**Comment by carlosfrodriguez** [comment]
Hi @s7design,

Thank you for your update, it was merge in https://github.com/OTRS/faq/commit/928cfc4596a03a86c64743d78aa9934db1a16b48, with small changes and unit test additions for FAQCount().

**Pull request closed without merging**
